package com.WorkMerge.enums;

public enum City {
	ACEBAL, ÁLVAREZ, ALVEAR, ARROYO_SECO, CARMEN_DEL_SAUCE, CAPITÁN_BERMÚDEZ, CORONEL_DOMÍNGUEZ, EMPALME,VILLA_CONSTITUCIÓN, FIGHIERA, FRAY_LUIS_BELTRÁN, FUNES, GENERAL_LAGOS, GRANADERO_BAIGORRIA, IBARLUCEA, PAVÓN, PÉREZ, PIÑERO, PUEBLO_ANDINO, PUEBLO_ESTHER, RICARDONE, ROSARIO, SAN_LORENZO, SOLDINI,VILLA_GOBERNADOR_GÁLVEZ,ZAVALLA}
